import { invoke } from "@tauri-apps/api/core";
import type {
  Blame,
  FileHistory,
  CompareMode,
  Comparison,
  Action,
  CommitBrief,
  CommitDetail,
  ConfigScope,
  GitSettings,
  RepoSettings,
  ConflictFile,
  DeletionCheck,
  FileDiff,
  History,
  MergePreview,
  Plan,
  RepoSummary,
  SearchQuery,
  SearchResult,
  Side,
  StashCheck,
  WorkingTree,
  RecentRepo,
  RepoGlance,
  WelcomeInfo,
  RemoteProbe,
  CloneOptions,
  NewRepoOptions,
  NewRepoPlan,
  GitCommand,
  OpEntry,
  Stack,
  StackPlan,
  StackPreview,
} from "./types";
import type { PullSetup } from "./remote";

export const api = {
  initialRepo: () => invoke<string | null>("initial_repo"),
  openRepo: (path: string) => invoke<RepoSummary>("open_repo", { path }),
  recentRepos: () => invoke<RecentRepo[]>("recent_repos"),
  /** With `to`, the repository moved there. */
  forgetRepo: (path: string, to: string | null = null) => invoke<void>("forget_repo", { path, to }),
  repoGlance: (path: string) => invoke<RepoGlance>("repo_glance", { path }),
  welcomeInfo: () => invoke<WelcomeInfo>("welcome_info"),
  folderState: (path: string) => invoke<"missing" | "empty" | "files" | "file">("folder_state", { path }),
  probeRemote: (url: string) => invoke<RemoteProbe>("probe_remote", { url }),
  cloneCommand: (options: CloneOptions) => invoke<GitCommand>("clone_command", { options }),
  /** Sends `clone-line` events while it runs; Stop is `stopAction`. */
  cloneRepo: (options: CloneOptions) => invoke<string>("clone_repo", { options }),
  planNewRepo: (options: NewRepoOptions) => invoke<NewRepoPlan>("plan_new_repo", { options }),
  createRepo: (options: NewRepoOptions) => invoke<string>("create_repo", { options }),
  history: () => invoke<History>("history"),
  commitDetail: (id: string) => invoke<CommitDetail>("commit_detail", { id }),
  commitDiff: (id: string, path: string | null, wholeFile: boolean) =>
    invoke<FileDiff[]>("commit_diff", { id, path, wholeFile }),
  compare: (base: string, target: string, mode: CompareMode) => invoke<Comparison>("compare", { base, target, mode }),
  compareDiff: (from: string, to: string, path: string | null, wholeFile: boolean) =>
    invoke<FileDiff[]>("compare_diff", { from, to, path, wholeFile }),
  fileHistory: (path: string, rev: string | null) => invoke<FileHistory>("file_history", { path, rev }),
  blame: (path: string, rev: string) => invoke<Blame>("blame", { path, rev }),
  lineHistory: (path: string, line: number, rev: string) => invoke<string[]>("line_history", { path, line, rev }),
  files: () => invoke<string[]>("files"),
  filePickaxe: (path: string, text: string, matchCase: boolean, rev: string) => invoke<string[]>("file_pickaxe", { path, text, matchCase, rev }),
  workingTree: () => invoke<WorkingTree>("working_tree"),
  workingDiff: (path: string, side: Side, wholeFile: boolean) => invoke<FileDiff>("working_diff", { path, side, wholeFile }),
  deletionCheck: (branch: string) => invoke<DeletionCheck>("deletion_check", { branch }),
  remoteDeletionCheck: (branch: string) => invoke<CommitBrief[]>("remote_deletion_check", { branch }),
  mergePreview: (branch: string) => invoke<MergePreview>("merge_preview", { branch }),
  conflictFile: (path: string) => invoke<ConflictFile>("conflict_file", { path }),
  stashCheck: (index: number, id: string) => invoke<StashCheck>("stash_check", { index, id }),
  stack: (branch: string | null) => invoke<Stack>("stack", { branch }),
  stackPreview: (plan: StackPlan) => invoke<StackPreview>("stack_preview", { plan }),
  planAction: (action: Action) => invoke<Plan>("plan_action", { action }),
  /** Rejects with a `Failure`. */
  performAction: (action: Action) => invoke<string>("perform_action", { action }),
  stopAction: () => invoke<void>("stop_action"),
  getSetting: <T>(key: string) => invoke<T | null>("get_setting", { key }),
  allSettings: () => invoke<Record<string, unknown>>("all_settings"),
  openSettings: () => invoke<void>("open_settings"),
  setSetting: (key: string, value: unknown) => invoke<void>("set_setting", { key, value }),
  gitSettings: () => invoke<GitSettings>("git_settings"),
  repoSettings: () => invoke<RepoSettings | null>("repo_settings"),
  /** `null` removes the value. */
  setGitConfig: (scope: ConfigScope, key: string, value: string | null) =>
    invoke<void>("set_git_config", { scope, key, value }),
  /** Sends `fetch-event`s while it runs; rejects with a `Failure`. */
  fetchInBackground: (remote: string | null) => invoke<{ updated: number }>("fetch_in_background", { remote }),
  stopFetch: () => invoke<void>("stop_fetch"),
  publicKey: (key: string) => invoke<string>("public_key", { key }),
  pullSetup: () => invoke<PullSetup>("pull_setup"),
  openInEditor: (path: string, line: number | null) => invoke<void>("open_in_editor", { path, line }),
  revealFile: (path: string) => invoke<void>("reveal_file", { path }),
  openInTerminal: () => invoke<void>("open_in_terminal"),
  monospaceFonts: () => invoke<string[]>("monospace_fonts"),
  refreshRemoteTags: () => invoke<boolean>("refresh_remote_tags"),
  /** Newest first. */
  operationLog: () => invoke<OpEntry[]>("operation_log"),
  search: (query: SearchQuery) => invoke<SearchResult>("search", { query }),
  settingsText: () => invoke<string>("settings_text"),
  saveSettingsText: (text: string) => invoke<void>("save_settings_text", { text }),
  /** settings.json and the copy Restore Defaults keeps, as typed in a shell. */
  settingsLocation: () => invoke<{ file: string; backup: string }>("settings_location"),
  restoreDefaultSettings: () => invoke<void>("restore_default_settings"),
  restoreSettingsBackup: () => invoke<void>("restore_settings_backup"),
  revealSettings: () => invoke<void>("reveal_settings"),
};

/** Keys of `settings.json`. */
export const settings = {
  detailsWidth: "oxbow.history.detailsWidth",
};
